"""HTML 결과 페이지 생성 (Jinja2 템플릿)."""

from jinja2 import Template

# ─────────────────────────────────────────────
# 매치별 HTML 템플릿
# ─────────────────────────────────────────────
MATCH_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>매치 결과 - {{ custom_match_id }}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Apple SD Gothic Neo', 'Malgun Gothic', sans-serif;
    background: #0F1419;
    color: #E5E7EB;
    padding: 24px;
    line-height: 1.6;
  }
  .container { max-width: 960px; margin: 0 auto; }
  .header {
    background: linear-gradient(135deg, #1F2937, #111827);
    padding: 24px;
    border-radius: 8px;
    margin-bottom: 24px;
    border-left: 4px solid #60A5FA;
  }
  .header h1 { font-size: 24px; margin-bottom: 8px; color: #F9FAFB; }
  .meta { color: #9CA3AF; font-size: 14px; }
  .meta span { margin-right: 16px; }
  .team {
    background: #1F2937;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 16px;
  }
  .team.blue { border-left: 4px solid #3B82F6; }
  .team.red { border-left: 4px solid #EF4444; }
  .team-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
    padding-bottom: 12px;
    border-bottom: 1px solid #374151;
  }
  .team-name { font-size: 18px; font-weight: 600; }
  .team.blue .team-name { color: #60A5FA; }
  .team.red .team-name { color: #F87171; }
  .result {
    padding: 4px 12px;
    border-radius: 4px;
    font-size: 13px;
    font-weight: 600;
  }
  .result.win { background: #064E3B; color: #6EE7B7; }
  .result.lose { background: #7F1D1D; color: #FCA5A5; }
  table { width: 100%; border-collapse: collapse; }
  th {
    text-align: left;
    padding: 8px 12px;
    font-size: 12px;
    color: #9CA3AF;
    font-weight: 500;
    border-bottom: 1px solid #374151;
  }
  td {
    padding: 12px;
    font-size: 14px;
    border-bottom: 1px solid #1F2937;
  }
  tr:last-child td { border-bottom: none; }
  .player { font-weight: 500; color: #F9FAFB; }
  .puuid { font-size: 11px; color: #6B7280; font-family: monospace; }
  .champion { color: #FBBF24; }
  .position { color: #9CA3AF; font-size: 12px; }
  .kda { font-family: 'SF Mono', 'Consolas', monospace; }
  .mmr-change {
    font-weight: 600;
    font-family: 'SF Mono', 'Consolas', monospace;
  }
  .mmr-change.up { color: #34D399; }
  .mmr-change.down { color: #F87171; }
  .mmr-progression {
    font-size: 12px;
    color: #9CA3AF;
    font-family: 'SF Mono', 'Consolas', monospace;
  }
  .footer {
    text-align: center;
    margin-top: 32px;
    padding: 16px;
    color: #6B7280;
    font-size: 12px;
  }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>매치 결과</h1>
    <div class="meta">
      <span>📋 {{ custom_match_id }}</span>
      <span>🏛 {{ guild_id }}</span>
      <span>📅 {{ match_date }}</span>
      <span>🎮 시즌 {{ season }}</span>
    </div>
  </div>

  {% for team_color, team_data in teams.items() %}
  <div class="team {{ team_color }}">
    <div class="team-header">
      <div class="team-name">{{ '🔵 BLUE' if team_color == 'blue' else '🔴 RED' }}</div>
      <span class="result {{ 'win' if team_data.is_win else 'lose' }}">
        {{ '승리' if team_data.is_win else '패배' }}
      </span>
    </div>
    <table>
      <thead>
        <tr>
          <th>플레이어</th>
          <th>챔피언</th>
          <th>포지션</th>
          <th>KDA</th>
          <th>MMR 변동</th>
        </tr>
      </thead>
      <tbody>
        {% for p in team_data.players %}
        <tr>
          <td>
            <div class="player">{{ p.riot_name }}</div>
            <div class="puuid">{{ p.puuid_short }}</div>
          </td>
          <td class="champion">{{ p.champion_name }}</td>
          <td class="position">{{ p.position }}</td>
          <td class="kda">{{ p.kill }} / {{ p.death }} / {{ p.assist }}</td>
          <td>
            <div class="mmr-change {{ 'up' if p.delta > 0 else 'down' }}">
              {{ '+' if p.delta > 0 else '' }}{{ p.delta }}
              {{ '↑' if p.delta > 0 else '↓' }}
            </div>
            <div class="mmr-progression">{{ p.pre_mmr }} → {{ p.post_mmr }}</div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endfor %}

  <div class="footer">
    Generated by MMR Pipeline · {{ generated_at }}
  </div>
</div>
</body>
</html>""")


def render_match_html(
  match_data: dict, mmr_results: list[dict], champion_lookup
) -> str:
  """
  매치 결과 HTML 생성.

  Args:
      match_data: payload 그대로
      mmr_results: calculate_match_mmr() 결과
      champion_lookup: champion_id → 한글 이름 함수
  """
  from datetime import datetime

  # puuid → mmr_result 매핑
  mmr_by_puuid = {r['puuid']: r for r in mmr_results}

  # 팀별로 그룹핑
  teams = {
    'blue': {'is_win': False, 'players': []},
    'red': {'is_win': False, 'players': []},
  }

  for p in match_data['participants']:
    team = p['game_team'].lower()
    if team not in teams:
      continue

    mmr_r = mmr_by_puuid.get(p['puuid'], {})
    teams[team]['is_win'] = p['game_result'] == '승'
    teams[team]['players'].append(
      {
        'riot_name': p.get('riot_name', 'Unknown'),
        'puuid_short': p['puuid'][:12] + '...',
        'champion_name': champion_lookup(p['champion_id']),
        'position': p['position'],
        'kill': p['kill'],
        'death': p['death'],
        'assist': p['assist'],
        'delta': mmr_r.get('delta', 0),
        'pre_mmr': mmr_r.get('pre_mmr', 0),
        'post_mmr': mmr_r.get('post_mmr', 0),
      }
    )

  return MATCH_TEMPLATE.render(
    custom_match_id=match_data['custom_match_id'],
    guild_id=match_data.get('guild_id', '-'),
    season=match_data.get('season', '-'),
    match_date=match_data.get('match_date', '-'),
    teams=teams,
    generated_at=datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC'),
  )
